/**
 * Maximum number of characters allowed in an Instagram/social caption.
 */
export const MAX_CAPTION_LENGTH = 2200;

/**
 * Combines a caption and an array of hashtags into a single string.
 *
 * - When `hashtags` is non-empty: returns `caption + "\n\n" + hashtags.join(" ")`
 * - When `hashtags` is empty or null/undefined: returns `caption` unchanged
 * - Throws if the combined result exceeds MAX_CAPTION_LENGTH (2200) characters
 *
 * This is a pure function with no side effects.
 *
 * @param caption  - The caption text written by the user or generated by AI
 * @param hashtags - Array of hashtag strings (e.g. ["#marketing", "#reels"])
 * @returns The final caption string ready for publishing
 * @throws {Error} When the resulting string exceeds 2200 characters
 */
export function buildFinalCaption(caption: string, hashtags: string[]): string {
  const result =
    hashtags && hashtags.length > 0
      ? `${caption}\n\n${hashtags.join(" ")}`
      : caption;

  if (result.length > MAX_CAPTION_LENGTH) {
    throw new Error(
      `Caption exceeds the maximum allowed length of ${MAX_CAPTION_LENGTH} characters (got ${result.length}).`
    );
  }

  return result;
}
