/**
 * frame-transformer.service.ts
 *
 * Applies professional style transfer to each extracted frame using
 * Stable Diffusion Ultra image-to-image via AWS Bedrock.
 *
 * The source frame is kept as the base — so the actual product/person/scene
 * from the user's video is preserved and simply given a professional look.
 * strength=0.45 keeps the subject recognisable while improving lighting,
 * colour and composition.
 */

import * as fs from "node:fs";
import * as path from "node:path";
import * as os from "node:os";
import * as crypto from "node:crypto";
import { styleTransferWithBedrock } from "@server/lib/bedrock";
import {
  downloadVideoArtifact,
  uploadVideoArtifact,
  buildJobS3Prefix,
} from "@server/lib/s3-video";
import { logger } from "@server/lib/logger";
import { isDevMode, buildLocalJobKey } from "@server/lib/local-storage";

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

const MAX_FRAMES_TO_TRANSFORM = 30;
const MAX_RETRIES = 2;

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface FrameTransformInput {
  frameIndex: number;
  s3Key: string;
  prompt: string;
}

export interface FrameTransformResult {
  frameIndex: number;
  s3Key: string;
  usedFallback: boolean;
  costUsd: number;
}

// ---------------------------------------------------------------------------
// transformFrames
// ---------------------------------------------------------------------------

/**
 * Transforms up to MAX_FRAMES_TO_TRANSFORM frames using Stable Diffusion Ultra.
 * Falls back to the original frame after 2 failures per frame.
 * Registers cost in CostLog for each successful Stable Diffusion call.
 */
export async function transformFrames(
  jobId: string,
  companyId: string,
  frames: FrameTransformInput[],
  visualStyle: string,
): Promise<FrameTransformResult[]> {
  const prefix = buildJobS3Prefix(jobId);
  const toProcess = frames.slice(0, MAX_FRAMES_TO_TRANSFORM);
  const results: FrameTransformResult[] = [];

  for (const frame of toProcess) {
    const result = await transformSingleFrame(
      jobId,
      companyId,
      frame,
      visualStyle,
      prefix,
    );
    results.push(result);
  }

  logger.info("[frame-transformer] All frames processed", {
    jobId,
    total: toProcess.length,
    fallbacks: results.filter((r) => r.usedFallback).length,
  });

  return results;
}

// ---------------------------------------------------------------------------
// Internal helpers
// ---------------------------------------------------------------------------

async function transformSingleFrame(
  jobId: string,
  companyId: string,
  frame: FrameTransformInput,
  visualStyle: string,
  s3Prefix: string,
): Promise<FrameTransformResult> {
  const outS3Key = isDevMode()
    ? buildLocalJobKey(jobId, `transformed/frame_${String(frame.frameIndex).padStart(4, "0")}.jpg`)
    : `${s3Prefix}transformed/frame_${String(frame.frameIndex).padStart(4, "0")}.jpg`;
  const tmpDir = path.join(os.tmpdir(), `tx-${jobId}-${frame.frameIndex}-${crypto.randomBytes(4).toString("hex")}`);
  fs.mkdirSync(tmpDir, { recursive: true });

  try {
    // Download original frame (used as fallback if SD fails)
    const originalBuffer = await downloadVideoArtifact(frame.s3Key);

    let transformedBuffer: Buffer | null = null;
    let costUsd = 0;

    // Image-to-image style transfer — preserves the actual product/subject
    // while giving it professional lighting, colour and composition.
    const sourceBase64 = originalBuffer.toString("base64");

    for (let attempt = 0; attempt < MAX_RETRIES; attempt++) {
      try {
        const result = await styleTransferWithBedrock(
          companyId,
          sourceBase64,
          `${frame.prompt}, ${visualStyle} style`,
          0.45,  // keep product recognisable
        );
        transformedBuffer = Buffer.from(result.imageBase64, "base64");
        costUsd = result.costUsd;
        break;
      } catch (err) {
        logger.warn(`[frame-transformer] Attempt ${attempt + 1} failed for frame ${frame.frameIndex}`, {
          jobId,
          error: err instanceof Error ? err.message : String(err),
        });
      }
    }

    const usedFallback = transformedBuffer === null;
    const finalBuffer = usedFallback ? originalBuffer : transformedBuffer!;

    await uploadVideoArtifact(outS3Key, finalBuffer, "image/jpeg");

    if (usedFallback) {
      logger.warn("[frame-transformer] Using fallback (original) for frame", {
        jobId,
        frameIndex: frame.frameIndex,
      });
    } else {
      logger.info("[frame-transformer] Frame generated by AI", {
        jobId,
        frameIndex: frame.frameIndex,
        costUsd,
      });
    }

    return { frameIndex: frame.frameIndex, s3Key: outS3Key, usedFallback, costUsd };
  } finally {
    try {
      fs.rmSync(tmpDir, { recursive: true, force: true });
    } catch { /* non-fatal */ }
  }
}
